name: Build assets
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v23
      - name: set node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: pcrgvg/statics
          path: statics
      - name: build dist
        run: |
          echo ${GITHUB_SHA}
          ng build --configuration production --deploy-url https://cdn.jsdelivr.net/gh/pcrgvg/statics@${GITHUB_SHA}/static/
      - name: commit to pcrgvg/statics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          push_options: '--force'
          tagging_message: "v$GITHUB_SHA"
          commit_message: ":bookmark: Release pcrgvg commit sha $GITHUB_SHA"
          repository: statics
          file_pattern: static/*