name: Build assets
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       env: 
         DATE: ${{date +%s}}
       - run: echo $DATE